#pragma once

#include <optional>

#include "hakoniwa/drone/control_adapter/altitude_control_backend.hpp"

namespace hakoniwa::drone::control_adapter {

struct Vector3D {
    double x{0.0};
    double y{0.0};
    double z{0.0};
};

struct PositionControl3DState {
    // Local/world-frame state in NED.
    Vector3D position{};
    Vector3D velocity{};
    Vector3D acceleration{};

    // Current attitude in the adapter convention.
    // The public adapter contract uses NED for world/local quantities and FRD
    // for body-frame quantities.
    AttitudeQuaternion attitude{};

    // Current yaw angle in the local/NED frame.
    double yaw_rad{0.0};
};

struct PositionControl3DPositionInput {
    PositionControl3DState state{};

    // Required position target in NED.
    Vector3D target_position{};

    // Optional feed-forward terms in NED. Backends that use PX4-style setpoint
    // semantics may translate missing values to NaN internally.
    std::optional<Vector3D> feedforward_velocity{};
    std::optional<Vector3D> feedforward_acceleration{};

    // Optional yaw setpoints. If absent, backends may hold the current yaw and
    // use zero yaw-rate feed-forward.
    std::optional<double> target_yaw_rad{};
    std::optional<double> target_yaw_rate_rad_sec{};
};

struct PositionControl3DVelocityInput {
    PositionControl3DState state{};

    // Required velocity target in NED.
    Vector3D target_velocity{};

    // Optional acceleration feed-forward in NED.
    std::optional<Vector3D> feedforward_acceleration{};

    // Optional yaw setpoints. If absent, backends may hold the current yaw and
    // use zero yaw-rate feed-forward.
    std::optional<double> target_yaw_rad{};
    std::optional<double> target_yaw_rate_rad_sec{};
};

struct PositionControl3DOutput {
    // Target attitude generated by the 3-axis position controller.
    AttitudeQuaternion target_attitude{};

    // Normalized collective thrust along body/FRD Z.
    // This intentionally reuses the existing altitude-control thrust contract.
    NormalizedVerticalThrustCommand thrust{};

    // Optional yaw-rate feed-forward associated with the target attitude.
    std::optional<double> target_yaw_rate_rad_sec{};

    // Optional backend-native diagnostic thrust vector.
    // For a PX4 backend this corresponds to the internal _thr_sp vector in
    // normalized NED thrust coordinates before conversion to attitude + body-z
    // collective thrust.
    std::optional<Vector3D> debug_thrust_sp{};
};

class IPositionControl3DBackend {
public:
    virtual ~IPositionControl3DBackend() = default;

    virtual void reset() = 0;

    virtual PositionControl3DOutput run_position(
        const PositionControl3DPositionInput& input,
        double dt_sec) = 0;

    virtual PositionControl3DOutput run_velocity(
        const PositionControl3DVelocityInput& input,
        double dt_sec) = 0;
};

}  // namespace hakoniwa::drone::control_adapter
